name = "MutatingOrNot"
uuid = "6a37069a-9a67-4b2d-a34a-f09ab4b23c7c"
authors = ["The ClimFlows contributors"]
version = "0.1.0"

[deps]
PackageExtensionCompat = "65ce6f38-6b18-4e1d-a461-8949797d7930"

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
ChainRulesCore_Ext = ["ChainRulesCore"]
Zygote_Ext = ["Zygote"]

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
